version: "3"
services:

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: app_nginx
    ports: 
      - "3000:80"

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root 
      MYSQL_ROOT_PASSWORD: johnahn
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    depends_on: 
      - mongo

  
  mongo:
    image: mongo:4.2.0
    restart: always
    container_name: app_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db