version: "3"
services:

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    depends_on:
      mongo:
        condition: service_healthy

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: app_nginx
    ports: 
      - "3000:80"
    depends_on:
      mongo:
        condition: service_healthy

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-hmadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-hmadminpass}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-owtdb}
      MONGODB_USERNAME: ${MONGODB_USERNAME:-hmuser}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-hmpass}
    depends_on:
      mongo:
        condition: service_healthy

  
  mongo:
    image: mongo:4.2.0
    restart: always
    container_name: app_mongodb
    ports:
      - "27017:27017"
    volumes:
      # - ./data/mongodb:/data/db
      - ./data/log/mongodb:/var/log/mongodb
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-hmadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-hmadminpass}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-owtdb}
      MONGODB_USERNAME: ${MONGODB_USERNAME:-hmuser}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-hmpass}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/owtdb --quiet
      timeout: 3s
      retries: 10